### ISSUE TITLE
feature: commitOnly

### ISSUE THREAD

**Issue by stefanbuck** [probot/semantic-pull-requests#31]
Would you accept a Pull Request which adds a `commitOnly` option similar to `titleOnly`?

**Comment by zeke** [comment]
Hi @stefanbuck  👋 

Sure, but would that mean "any commit" or "all commits"?

**Comment by stefanbuck** [comment]
Mhhh ... in my opinion it should be "all commits" to keep it simple.

**Comment by zeke** [comment]
That sounds fine to me. Let's just make sure to use a name that is clear.

**Comment by cilindrox** [comment]
was just about to propose the same, [this `or` here](https://github.com/probot/semantic-pull-requests/blob/master/lib/handle-pull-request-change.js#L23) is causing some sneaky messages to appear upstream :P

**Comment by zeke** [comment]
> some sneaky messages

@cilindrox can you clarify what you mean by this. Wanna make sure I understand you.

**Comment by zeke** [comment]
> some sneaky messages

@cilindrox can you clarify what you mean by this. Wanna make sure I understand you.

**Comment by cilindrox** [comment]
@stefanbuck eg - someone creates a pr with the following commit list:

```
chore: update role
build: bump dockerfile
Merge remote-tracking branch 'upstream/master'
build: update tag
```
That should `fail` with a pending status, but instead, it passes due to the `[].some()` filter.

**Comment by zeke** [comment]
☝️ That actually shouldn't fail. The default behavior of the bot is not to police all commits, but to ensure the PR has _just enough_ semantic information to be able to trigger a new release if needed.

It seems this is a common misconception. I will update the README to make this more clear.

**Comment by zeke** [comment]
Opened https://github.com/probot/semantic-pull-requests/pull/32

**Comment by cilindrox** [comment]
Thanks for clarifying, appreciate it @zeke Guess I'll need to deploy a fork then

**Comment by zeke** [comment]
@cilindrox I wouldn't want anyone to have to maintain a fork. If you want to support another behavior, let's talk about it and see if we can enable it with configuration.

**Comment by cilindrox** [comment]
@zeke glad to hear :)

I'm thinking about adding a `strict` setting, which could work by auditing either `some` or `every` commit message.

eg:

```yaml
// semantic.yaml
strict: "allCommits" || "anyCommits"
```

Invalid syntax, but guess it conveys the point. That should take care of this original issue's premise and tackle a strict mode (sorry for hijacking it btw)

Thoughts?

**Comment by nathanielc** [comment]
I would similarly support a `commitsOnly: true` option. I want to validate all commits and do not care about the PR title, this is because we primarily use the Rebase+Merge method in github.

I don't have an opinion on the name of the configuration option so long as it is clear.

**Comment by zeke** [comment]
Okay. Let's do `commitsOnly`. When enabled, the bot will ignore the PR title and require  **all commits** to be semantic.

**Comment by zeke** [comment]
Anyone want to take a shot at implementing this?

**Comment by stefanbuck** [comment]
I'm close to raise a Pull Request soon
