### ISSUE TITLE
feature: custom types

### ISSUE THREAD

**Issue by nathanielc** [probot/semantic-pull-requests#34]
Would a PR to add configuration for accepting additional commit types be accepted?

Something along the lines of:

```
additionalTypes: 
    - foo
    - bar
    - baz
```

This would validate the message type is one of these types https://github.com/commitizen/conventional-commit-types/blob/master/index.json or one of the additional types.

According to the SPEC other types may be added. https://www.conventionalcommits.org/en/v1.0.0-beta.2/#specification I would like to explicitly configure those types.

**Comment by zeke** [comment]
Yeah this sounds like a good idea. Go for it!

**Comment by mrchief** [comment]
`parse-commit-message` package doesn't actually care about the type, it just checks if it exists and is a string: https://github.com/tunnckoCoreLabs/parse-commit-message/blob/master/src/header.js#L152

So this should already be possible unless I'm missing some connection.

**Comment by amoshydra** [comment]
@mrchief `parse-commit-message` indeed doesn't care about the type

However semantic-pull-requests does:

https://github.com/probot/semantic-pull-requests/blob/df5cba1a7ca11af18713af2a1e05e7252efa49f3/lib/is-semantic-message.js#L18

Therefore, PR title like "improvement: Enhance navbar" will not pass as a semantic message.

**Comment by amoshydra** [comment]
@mrchief I was thinking the same too (*allowing additional types to be passed in*).

I have made a PR to do that #67

**Comment by php-coder** [comment]
It seems like this issue can be closed now?

BTW I found it a little confusing because to me "additional types" is something that add more types while the implementation is more about "override types". I know it's not so hard to copy&paste around 10 existing types but it still could be easier if there will be "additionalTypes"/"customTypes" or "extraTypes" field.

**Comment by zeke** [comment]
Yep this was resolved by #67, thanks for pointing that out.

>  I found it a little confusing because to me "additional types" is something that add more types

☝️ The key that ended up in the implementation is called `types`, so there shouldn't be much confusion now. If you need all the existing types plus others, you can enumerate them all in the `types` array. See https://github.com/probot/semantic-pull-requests#configuration
