### ISSUE TITLE
If I wanted to use this in private enterprise GIthub...

### ISSUE THREAD

**Issue by rodoabad** [probot/semantic-pull-requests#45]
It looks like I can't just "use it" like what most tutorials suggest.

Does this mean I have to fork this repository internally, build it, deploy to our cloud provider like AWS, and then use it internally?

**Comment by zeke** [comment]
Hi @rodoabad. I don't know much about it, but after a quick search in issues across the @probot org, it appears that your assumption is correct: https://github.com/probot/probot/issues/500#issuecomment-381266516

> To use a GitHub App (or a Probot App) on GitHub Enterprise, you'll need to have your own deployment. You can follow the deployment docs to get started. The only difference is that you'll need to add this environment variable:

**Comment by zeke** [comment]
Gonna go ahead and close this due to inactivity. Feel free to comment if this merits more discussion.
