### ISSUE TITLE
Maybe semantic PR titles won't work

### ISSUE THREAD

**Issue by zeke** [probot/semantic-pull-requests#5]
I was thinking pull request titles were used as the default merge and squash commit message, but I was wrong. They are the default `body` of the commit, not the `subject` 🤔 

So, it seems a semantic PR title will __not__ suffice for a triggering a semantic release:

<img width="790" alt="screen shot 2018-02-27 at 4 53 50 pm" src="https://user-images.githubusercontent.com/2289/36763937-0ab993be-1bdf-11e8-8e64-7a17a435bc56.png">

Thoughts on working around this, @groundwater and @gr2m?

**Comment by gr2m** [comment]
semantic-release is quite modular now, it has `analyzeNotes` and `generateNotes` extension points that you could customize to look for the prefixes in the first line of the commit body if the commit subject starts with `Merge pull request #`

https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/configuration.html#analyzecommits

**Comment by bkeepers** [comment]
I think it works if you force squashing of merges.

**Comment by zeke** [comment]
> force squashing of merges.

Yeah.. the Electron maintainers group wants to leave our PR merging options open. Everyone seems to have a use case for which they need squashing, rebasing, or merging. So it would be ideal to make this thing work for any pull-request-landing strategy.
