### ISSUE TITLE
Discrepancy between listed semantic PR titles and those approved by PR bot

### ISSUE THREAD

**Issue by matthewfeickert** [probot/semantic-pull-requests#72]
Hi. We use the Semantic Pull Request bot on our project [pyhf](https://github.com/diana-hep/pyhf). However, we've noticed that the bot doesn't recognize PRs that start with the `improvement` keyword as being semantic (examples: pyhf [PR 596](https://github.com/diana-hep/pyhf/pull/596) and [PR 541](https://github.com/diana-hep/pyhf/pull/541)) though it is listed in the link off of the `README` to `commitizen/conventional-commit-types`

> PR title is [semantic](https://github.com/commitizen/conventional-commit-types/blob/master/index.json)

I see that this is because `improvement` was added to `commitizen/conventional-commit-types` less than 2 weeks ago in their [PR 13](https://github.com/commitizen/conventional-commit-types/pull/13) and the Semantic Pull Request bot uses `v2.2.0` of `commitizen/conventional-commit-types` &mdash; which was [released in 2017](https://github.com/commitizen/conventional-commit-types/releases/tag/v2.2.0).

I just wanted to report this, but I guess I should also ask if you plan on only supporting the types that are in releases of `commitizen/conventional-commit-types`. If so, I guess I should bug them RE: the possibility of a new release in 2019.

cc @kratsg @lukasheinrich

**Comment by zeke** [comment]
Hey @matthewfeickert 👋 

Judging by https://github.com/commitizen/conventional-commit-types/pull/13#issuecomment-549189892, it looks like `improvement` was removed from the 1.0.0 spec after all. Is that correct? If so, can this issue be closed?

Note that you can work around this by specifying a `types` array in `.github/semantic.yml`. See https://github.com/probot/semantic-pull-requests#configuration
